aliases:
  display cpu-us: display cpu
  display cpu-usage: display cpu
  display ip int brief: display ip interface brief
  display vrrp statis: display vrrp statistics
  show env power: show environment power
  show env fan: show environment fan
  show env temp: show environment temperature
  show env temperature: show environment temperature
  show int status: show interface status
  show ip int brief: show ip interface brief
  show proc cpu: show processes cpu
  show proc memory: show processes memory
