from django.urls import path

from . import auth, user_admin
from .views import chat, conversations, health, itsm, knowledge, notifications, rag, skills, storage, system, tasks, upload, workflows

urlpatterns = [
    path("auth/login/", auth.bff_login, name="bff_login"),
    path("auth/refresh/", auth.bff_refresh, name="bff_refresh"),
    path("auth/logout/", auth.bff_logout, name="bff_logout"),
    path("auth/me/", auth.bff_me, name="bff_me"),
    path("auth/change-password/", auth.bff_change_password, name="bff_change_password"),
    path("auth/users/", user_admin.bff_users_list_or_create, name="bff_users"),
    path("auth/users/<int:user_id>/", user_admin.bff_user_detail, name="bff_user_detail"),
    path(
        "auth/users/<int:user_id>/reset-password/",
        user_admin.bff_user_reset_password,
        name="bff_user_reset_password",
    ),
    path("chat/", chat.proxy_chat, name="bff_chat"),
    path("chat/stream/", chat.proxy_chat_stream, name="bff_chat_stream"),
    path("chat/upload/", upload.proxy_chat_upload, name="bff_chat_upload"),
    path("health/", health.proxy_health, name="bff_health"),
    path("health/diagnostics/", health.proxy_health_diagnostics, name="bff_health_diagnostics"),
    path("gateway/", system.proxy_gateway_info, name="bff_gateway_info"),
    path("tasks/<str:task_id>/", tasks.proxy_task_status, name="bff_task_status"),
    path("workflows/templates/", workflows.proxy_workflow_templates, name="bff_workflow_templates"),
    path("workflows/templates/<str:name>/dsl/", workflows.proxy_workflow_template_dsl, name="bff_workflow_template_dsl"),
    path("workflows/templates/<str:name>/", workflows.proxy_workflow_template_detail, name="bff_workflow_template_detail"),
    path("workflows/reload/", workflows.proxy_workflow_reload, name="bff_workflow_reload"),
    path("workflows/validate/", workflows.proxy_workflow_validate, name="bff_workflow_validate"),
    path("workflows/preview/", workflows.proxy_workflow_preview, name="bff_workflow_preview"),
    path("workflows/generate/", workflows.proxy_workflow_generate, name="bff_workflow_generate"),
    path("workflows/infer-mappings/", workflows.proxy_workflow_infer_mappings, name="bff_workflow_infer_mappings"),
    path("workflows/dry-run/", workflows.proxy_workflow_dry_run, name="bff_workflow_dry_run"),
    path("workflows/chat-intent/suggest-nl/", workflows.proxy_chat_intent_suggest_nl, name="bff_chat_intent_suggest_nl"),
    path("workflows/categories/", workflows.proxy_workflow_categories, name="bff_workflow_categories"),
    path("workflows/expression-hints/preview/", workflows.proxy_workflow_expression_hints_preview, name="bff_workflow_expression_hints"),
    path("workflows/plugins/", workflows.proxy_workflow_plugins, name="bff_workflow_plugins"),
    path("workflows/import/", workflows.proxy_workflow_import, name="bff_workflow_import"),
    path("workflows/plugins/<str:name>/versions/diff/", workflows.proxy_plugin_version_diff, name="bff_plugin_version_diff"),
    path("workflows/plugins/<str:name>/versions/", workflows.proxy_plugin_versions, name="bff_plugin_versions"),
    path("workflows/plugins/<str:name>/export/", workflows.proxy_plugin_export, name="bff_plugin_export"),
    path("workflows/plugins/<str:name>/submit-review/", workflows.proxy_plugin_submit_review, name="bff_plugin_submit_review"),
    path("workflows/plugins/<str:name>/publish/", workflows.proxy_plugin_publish, name="bff_plugin_publish"),
    path("workflows/plugins/<str:name>/reject/", workflows.proxy_plugin_reject, name="bff_plugin_reject"),
    path("workflows/plugins/<str:name>/publish-to-market/", workflows.proxy_plugin_publish_market, name="bff_plugin_publish_market"),
    path("workflows/plugins/<str:name>/", workflows.proxy_plugin_delete, name="bff_plugin_delete"),
    path("workflows/market/templates/", workflows.proxy_market_templates, name="bff_market_templates"),
    path("workflows/market/templates/<str:template_id>/", workflows.proxy_market_template_detail, name="bff_market_template_detail"),
    path("workflows/chat-intent/preview/", workflows.proxy_chat_intent_preview, name="bff_chat_intent_preview"),
    path("workflows/runs/", workflows.proxy_workflow_runs, name="bff_workflow_runs"),
    path("workflows/runs/test/", workflows.proxy_workflow_test_run, name="bff_workflow_test_run"),
    path("workflows/<str:run_id>/timeline/", workflows.proxy_workflow_timeline, name="bff_workflow_timeline"),
    path("workflows/<str:run_id>/events/stream/", workflows.proxy_workflow_events_stream, name="bff_workflow_events_stream"),
    path("workflows/<str:run_id>/", workflows.proxy_workflow_detail, name="bff_workflow_detail"),
    path("notifications/", notifications.proxy_notifications_list, name="bff_notifications"),
    path("notifications/clear/", notifications.proxy_notifications_clear, name="bff_notifications_clear"),
    path(
        "notifications/<str:notification_id>/read/",
        notifications.proxy_notification_read,
        name="bff_notification_read",
    ),
    path("conversations/", conversations.proxy_conversations, name="bff_conversations"),
    path(
        "conversations/<str:conversation_id>/",
        conversations.proxy_conversation_detail,
        name="bff_conversation_detail",
    ),
    path(
        "conversations/<str:conversation_id>/messages/",
        conversations.proxy_add_message,
        name="bff_add_message",
    ),
    path(
        "conversations/<str:conversation_id>/summarize/",
        conversations.proxy_summarize_conversation,
        name="bff_summarize_conversation",
    ),
    path("rag/search/", rag.proxy_rag_search, name="bff_rag_search"),
    path("itsm/webhook/", itsm.proxy_itsm_webhook, name="bff_itsm_webhook"),
    path(
        "itsm/webhook/firewall-policy/",
        itsm.proxy_firewall_policy_webhook,
        name="bff_itsm_firewall_policy",
    ),
    path("itsm/webhook/callback/", itsm.proxy_itsm_callback, name="bff_itsm_callback"),
    path("skills/", skills.proxy_skills_list, name="bff_skills_list"),
    path("skills/stats/", skills.proxy_skills_stats, name="bff_skills_stats"),
    path("skills/reload-all/", skills.proxy_reload_all_skills, name="bff_skills_reload_all"),
    path("skills/<str:skill_name>/content/", skills.proxy_skill_content, name="bff_skill_content"),
    path("skills/<str:skill_name>/files/", skills.proxy_skill_files, name="bff_skill_files"),
    path("skills/<str:skill_name>/toggle/", skills.proxy_skill_toggle, name="bff_skill_toggle"),
    path("skills/<str:skill_name>/reload/", skills.proxy_skill_reload, name="bff_skill_reload"),
    path("skills/<str:skill_name>/test-run/", skills.proxy_skill_test_run, name="bff_skill_test_run"),
    path("skills/<str:skill_name>/schema/", skills.proxy_skill_schema, name="bff_skill_schema"),
    path("skills/<str:skill_name>/", skills.proxy_skill_detail, name="bff_skill_detail"),
    path("knowledge/documents/", knowledge.proxy_knowledge_documents, name="bff_knowledge_documents"),
    path(
        "knowledge/documents/<path:doc_path>/content/",
        knowledge.proxy_knowledge_document_content,
        name="bff_knowledge_document_content",
    ),
    path(
        "knowledge/documents/<path:doc_path>/",
        knowledge.proxy_knowledge_document_detail,
        name="bff_knowledge_document_detail",
    ),
    path("knowledge/stats/", knowledge.proxy_knowledge_stats, name="bff_knowledge_stats"),
    path("knowledge/reindex/", knowledge.proxy_knowledge_reindex, name="bff_knowledge_reindex"),
    path("storage/health/", storage.proxy_storage_health, name="bff_storage_health"),
    path("storage/teams/", storage.proxy_storage_teams, name="bff_storage_teams"),
    path("storage/teams/<str:team_id>/", storage.proxy_storage_team_detail, name="bff_storage_team_detail"),
    path("storage/teams/<str:team_id>/members/", storage.proxy_storage_team_members, name="bff_storage_team_members"),
    path(
        "storage/teams/<str:team_id>/members/<str:member_user_id>/",
        storage.proxy_storage_team_member_detail,
        name="bff_storage_team_member_detail",
    ),
    path("storage/folders/tree/", storage.proxy_storage_folder_tree, name="bff_storage_folder_tree"),
    path("storage/folders/", storage.proxy_storage_folders, name="bff_storage_folders"),
    path("storage/folders/<str:folder_id>/move/", storage.proxy_storage_folder_move, name="bff_storage_folder_move"),
    path("storage/folders/<str:folder_id>/", storage.proxy_storage_folder_detail, name="bff_storage_folder_detail"),
    path("storage/list/", storage.proxy_storage_list, name="bff_storage_list"),
    path("storage/upload/init/", storage.proxy_storage_upload_init, name="bff_storage_upload_init"),
    path("storage/upload/complete/", storage.proxy_storage_upload_complete, name="bff_storage_upload_complete"),
    path("storage/files/<str:file_id>/content/", storage.proxy_storage_file_content, name="bff_storage_file_content"),
    path("storage/files/<str:file_id>/download/", storage.proxy_storage_file_download, name="bff_storage_file_download"),
    path("storage/files/<str:file_id>/copy/", storage.proxy_storage_file_copy, name="bff_storage_file_copy"),
    path("storage/files/<str:file_id>/move/", storage.proxy_storage_file_move, name="bff_storage_file_move"),
    path("storage/files/<str:file_id>/", storage.proxy_storage_file_detail, name="bff_storage_file_detail"),
    path("storage/share/", storage.proxy_storage_share, name="bff_storage_share"),
    path("storage/share/folder/", storage.proxy_storage_share_folder, name="bff_storage_share_folder"),
]
