Set-Location -LiteralPath 'c:\Users\wangd\PycharmProjects\PythonProject\netops-agent'
$env:DEBUG='true'
$env:ENFORCE_BFF_ORIGIN='false'
$env:USE_SUPERVISOR_V2='true'
$env:POSTGRES_HOST='localhost'
$env:REDIS_HOST='localhost'
$env:QDRANT_HOST='localhost'
$env:MINIO_ENDPOINT='localhost:9000'
$env:JWT_SECRET_KEY='my-secret-key-2026-netops'
$env:DEEPSEEK_API_KEY='sk-2b4b2563518345c7833fbd4c520e3258'
$env:POSTGRES_PASSWORD='netops123456'
$env:POSTGRES_USER='netops'
$env:POSTGRES_DB='netops_agent'
$env:POSTGRES_PORT='5432'

& 'c:\Users\wangd\PycharmProjects\PythonProject\netops-agent\venv\Scripts\python.exe' -m uvicorn src.gateway.main:app --host 0.0.0.0 --port 8000 --reload 2>&1 | Tee-Object -FilePath 'c:\Users\wangd\PycharmProjects\PythonProject\netops-agent\.runtime\test\fastapi.log'
